name: Check formatting

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Run ktLintCheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Check Formatting
        run: ./gradlew kC